@api=http://localhost:3000/api

### register
POST {{api}}/auth/register
Content-Type: application/json

{
    "firstName": "Another7",
    "lastName": "User7",
    "email": "test7@email.com",
    "password": "0000"
}

### login
POST {{api}}/auth/login
Content-Type: application/json

{
    "email": "test7@email.com",
    "password": "0000"
}