@api=http://localhost:3000/api


### Login
# @name auth
POST {{api}}/auth/login
Content-Type: application/json

{
    "email": "test@email.com",
    "password": "0000"
}


### Create project
# @name createProject
POST {{api}}/project/create
# Authorization: Bearer {{auth.response.body.token}}
Content-Type: application/json

{
    "name": "test name7",
    "description": "test description",
    "features": [
        {
            "title": "test title of feature5",
            "level": "1.1",
            "estimate": 5
        },
        {
            "title": "test title of feature5",
            "level": "1.2",
            "estimate": 5
        }
    ]
}

### Update project
# @name updateProject
PUT {{api}}/project/update
Content-Type: application/json

{   
    "_id": "5fb03598bee8f12c84f9d8bb",
    "name": "test updated 15",
    "description": "test description 15",
    "features": [
        {
            "title": "test title",
            "level": "1",
            "estimate": 12
        },
        {
            "title": "test title of feature5",
            "level": "1",
            "estimate": 12
        }
    ]
}
