@api=http://localhost:3000/api


### Login
# @name auth
POST {{api}}/auth/login
Content-Type: application/json

{
    "email": "test@email.com",
    "password": "0000"
}


### Create project
# @name createProject
POST {{api}}/project/create
# Authorization: Bearer {{auth.response.body.token}}
Content-Type: application/json

{
    "project": {
        "name": "test name2",
        "description": "test description",
        "features": [
            {
                "title": "test title of feature3",
                "level": "1.1",
                "estimate": 5
            },
            {
                "title": "test title of feature3",
                "level": "1.2",
                "estimate": 5
            }
        ]
    }
}